contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.0.0
    itemVersion: 1.0.9
    packID: ""
    packName: Digital Shadows SearchLight
    toServerVersion: ""
description: Enrichment of SHA1 IOC types - sub-playbook for IOC Assessment & Enrichment
  playbook
id: 'Digital Shadows - SHA1_IoC Assessment & Enrichment_v2'
inputs:
- description: A Digital Shadows ShadowSearch query containing SHA1 hashes
  key: IoC_SHA1
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: SHA1
      root: File
      transformers:
      - operator: uniq
name: Digital Shadows - SHA1_IoC Assessment & Enrichment_v2
outputs:
- contextPath: DBotScore.Indicator
  description: Indicator Value
  type: string
- contextPath: DBotScore.Type
  description: Indicator Type
  type: string
sourceplaybookid: Digital Shadows - SHA1_IoC Assessment & Enrichment
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "54"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0af24832-6cf1-4605-808b-d486167c8451
      iscommand: false
      name: ""
      version: -1
    taskid: 0af24832-6cf1-4605-808b-d486167c8451
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 50
        }
      }
  "13":
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8c405794-27f0-48da-89da-01c476ea8d6c
      iscommand: false
      name: End
      type: title
      version: -1
    taskid: 8c405794-27f0-48da-89da-01c476ea8d6c
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1260
        }
      }
  "44":
    continueonerrortype: ""
    id: "44"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "45"
    note: false
    quietmode: 0
    scriptarguments:
      extend-context:
        simple: SHA1 Associated Indicators=content.entity.indicators.title
      filter_types:
        simple: INDICATOR_FEED
      query:
        simple: ${inputs.IoC_SHA1}
      sort_property:
        simple: sortDate
    separatecontext: false
    skipunavailable: false
    task:
      brand: Digital Shadows V2
      description: Perform a general search against incidents, threats closed sources,
        etc.
      id: 38c8644b-e5a2-4c32-8225-0935f045eef3
      iscommand: true
      name: ds-search - THREAT FEEDS
      script: Digital Shadows V2|||ds-search
      type: regular
      version: -1
    taskid: 38c8644b-e5a2-4c32-8225-0935f045eef3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 895
        }
      }
  "45":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${SHA1 Associated Indicators}
          operator: isEmpty
      label: "yes"
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${SHA1 Associated Indicators}
          operator: isNotEmpty
      label: "no"
    continueonerrortype: ""
    id: "45"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "56"
      "yes":
      - "13"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8e932ebb-3422-41e2-80b1-2c1fd839a03d
      iscommand: false
      name: is Associated Indicators blank?
      type: condition
      version: -1
    taskid: 8e932ebb-3422-41e2-80b1-2c1fd839a03d
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1070
        }
      }
  "48":
    continueonerrortype: ""
    id: "48"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "49"
      - "44"
    note: false
    quietmode: 0
    scriptarguments:
      extend-context:
        simple: SHA1 Intel Summary=content.entity.summary
      filter_types:
        simple: INTEL_INCIDENT
      query:
        simple: ${inputs.IoC_SHA1}
      sort_property:
        simple: sortDate
    separatecontext: false
    skipunavailable: false
    task:
      brand: Digital Shadows V2
      description: Perform a general search against incidents, threats closed sources,
        etc.
      id: 4ba22692-9325-428c-817a-cdfca9183c2a
      iscommand: true
      name: ds-search - INTEL UPDATES
      script: Digital Shadows V2|||ds-search
      type: regular
      version: -1
    taskid: 4ba22692-9325-428c-817a-cdfca9183c2a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
  "49":
    continueonerrortype: ""
    id: "49"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      desc:
        simple: Summary
      description:
        simple: ${SHA1 Intel Summary}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Adds provided entries to the incident Evidence Board. In playbook, can be positioned after a task to add the previous task's entries to Evidence Board automatically (with no need to provide arguments)
      id: db8e13b4-7741-4ea4-8eb8-c942366505c8
      iscommand: false
      name: AddEvidence - INTEL UPDATES
      script: AddEvidence
      type: regular
      version: -1
    taskid: db8e13b4-7741-4ea4-8eb8-c942366505c8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 895
        }
      }
  "50":
    continueonerrortype: ""
    id: "50"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "51"
      - "48"
    note: false
    quietmode: 0
    scriptarguments:
      extend-context:
        simple: SHA1 Profile Name=content.entity.primaryTag.name
      filter_types:
        simple: INTELLIGENCE
      query:
        simple: ${inputs.IoC_SHA1}
      sort_property:
        simple: sortDate
    separatecontext: false
    skipunavailable: false
    task:
      brand: Digital Shadows V2
      description: Perform a general search against incidents, threats closed sources,
        etc.
      id: 1d65ba4a-afa1-4b02-8abb-396516d94211
      iscommand: true
      name: ds-search - PROFILE INTELLIGENCE
      script: Digital Shadows V2|||ds-search
      type: regular
      version: -1
    taskid: 1d65ba4a-afa1-4b02-8abb-396516d94211
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 545
        }
      }
  "51":
    continueonerrortype: ""
    id: "51"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      desc:
        simple: Profiles
      description:
        simple: ${SHA1 Profile Name}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Adds provided entries to the incident Evidence Board. In playbook, can be positioned after a task to add the previous task's entries to Evidence Board automatically (with no need to provide arguments)
      id: f85fa319-9bf8-4e1b-824d-5641f77542e5
      iscommand: false
      name: AddEvidence - INTEL PROFILES
      script: AddEvidence
      type: regular
      version: -1
    taskid: f85fa319-9bf8-4e1b-824d-5641f77542e5
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 720
        }
      }
  "52":
    continueonerrortype: ""
    id: "52"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "53"
      - "50"
    note: false
    quietmode: 0
    scriptarguments:
      extend-context:
        simple: SHA1 TTP Profiles=content.entity.primaryTag.name
      filter_types:
        simple: TECHNIQUE
      query:
        simple: ${inputs.IoC_SHA1}
      sort_property:
        simple: sortDate
    separatecontext: false
    skipunavailable: false
    task:
      brand: Digital Shadows V2
      description: Perform a general search against incidents, threats closed sources,
        etc.
      id: de6485f9-fcba-44cd-8004-4c9a21e20a48
      iscommand: true
      name: ds-search - MITRE TECHNIQUES
      script: Digital Shadows V2|||ds-search
      type: regular
      version: -1
    taskid: de6485f9-fcba-44cd-8004-4c9a21e20a48
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 370
        }
      }
  "53":
    continueonerrortype: ""
    id: "53"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      desc:
        simple: Associated TTPs
      description:
        simple: ${SHA1 TTP Profiles}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Adds provided entries to the incident Evidence Board. In playbook, can be positioned after a task to add the previous task's entries to Evidence Board automatically (with no need to provide arguments)
      id: e07f6962-720f-420e-88e4-f1775bea531a
      iscommand: false
      name: AddEvidence - MITRE TECHNIQUES
      script: AddEvidence
      type: regular
      version: -1
    taskid: e07f6962-720f-420e-88e4-f1775bea531a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 545
        }
      }
  "54":
    continueonerrortype: ""
    id: "54"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "55"
      - "52"
    note: false
    quietmode: 0
    scriptarguments:
      extend-context:
        simple: SHA1 Confirmed Activity=total
      filter_types:
        simple: INDICATOR_FEED
      query:
        simple: ${inputs.IoC_SHA1}
      sort_property:
        simple: sortDate
    separatecontext: false
    skipunavailable: false
    task:
      brand: Digital Shadows V2
      description: Perform a general search against incidents, threats closed sources,
        etc.
      id: 461dbdb5-69b4-4bcb-8ad0-6513e6e7554d
      iscommand: true
      name: ds-search - CONFIRMED ACTIVITY
      script: Digital Shadows V2|||ds-search
      type: regular
      version: -1
    taskid: 461dbdb5-69b4-4bcb-8ad0-6513e6e7554d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 195
        }
      }
  "55":
    continueonerrortype: ""
    id: "55"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      desc:
        simple: Confirmed Malicious Activity Count
      description:
        simple: ${SHA1 Confirmed Activity}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Adds provided entries to the incident Evidence Board. In playbook,
        can be positioned after a task to add the previous task's entries to Evidence
        Board automatically (with no need to provide arguments)
      id: 6c378cbb-cafa-4b33-8d4c-0c621f58bf35
      iscommand: false
      name: AddEvidence - CONFIRMED ACTIVITY
      script: AddEvidence
      type: regular
      version: -1
    taskid: 6c378cbb-cafa-4b33-8d4c-0c621f58bf35
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 370
        }
      }
  "56":
    continueonerrortype: ""
    id: "56"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${SHA1 Associated Indicators}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 245d5fcb-f328-4f7f-8fcd-b642e3bea836
      iscommand: false
      name: Print Associated Indicators
      script: Print
      type: regular
      version: -1
    taskid: 245d5fcb-f328-4f7f-8fcd-b642e3bea836
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1245
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1290,
        "width": 1670,
        "x": 50,
        "y": 50
      }
    }
  }
