contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.0.0
    itemVersion: 1.0.9
    packID: ""
    packName: Digital Shadows SearchLight
    toServerVersion: ""
description: Enrichment of CVE IOC types - sub-playbook for IOC Assessment & Enrichment
  playbook
id: 'Digital Shadows - CVE_IoC Assessment & Enrichment_v2'
inputs:
- description: A Digital Shadows ShadowSearch query containing CVE IDs
  key: IoC_CVE
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: ID
      root: CVE
      transformers:
      - operator: uniq
name: Digital Shadows - CVE_IoC Assessment & Enrichment_v2
outputs:
- contextPath: DBotScore.Indicator
  description: Indicator Value
  type: string
- contextPath: DBotScore.Type
  description: Indicator Type
  type: string
sourceplaybookid: Digital Shadows - CVE_IoC Assessment & Enrichment
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "18"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 32dabdab-88b2-4433-8198-8a8d7e4984b7
      iscommand: false
      name: ""
      version: -1
    taskid: 32dabdab-88b2-4433-8198-8a8d7e4984b7
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
  "13":
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d13911d2-7aac-456f-890b-defcbf43969b
      iscommand: false
      name: End
      type: title
      version: -1
    taskid: d13911d2-7aac-456f-890b-defcbf43969b
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 910,
          "y": 1260
        }
      }
  "18":
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "19"
      - "20"
    note: false
    quietmode: 0
    scriptarguments:
      extend-context:
        simple: CVE Confirmed Activity=total
      filter_types:
        simple: INDICATOR_FEED
      query:
        simple: ${inputs.IoC_CVE}
      sort_property:
        simple: sortDate
    separatecontext: false
    skipunavailable: false
    task:
      brand: Digital Shadows V2
      description: Perform a general search against incidents, threats closed sources,
        etc.
      id: 4a14aa85-0952-4bff-8849-95d43706690d
      iscommand: true
      name: ds-search - CONFIRMED ACTIVITY
      script: Digital Shadows V2|||ds-search
      type: regular
      version: -1
    taskid: 4a14aa85-0952-4bff-8849-95d43706690d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
  "19":
    continueonerrortype: ""
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      desc:
        simple: Confirmed Malicious Activity Count
      description:
        simple: ${CVE Confirmed Activity}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Adds provided entries to the incident Evidence Board. In playbook, can be positioned after a task to add the previous task's entries to Evidence Board automatically (with no need to provide arguments)
      id: 924d5566-1e8f-4d28-8fda-a5508c97020f
      iscommand: false
      name: AddEvidence - CONFIRMED ACTIVITY
      script: AddEvidence
      type: regular
      version: -1
    taskid: 924d5566-1e8f-4d28-8fda-a5508c97020f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "20":
    continueonerrortype: ""
    id: "20"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "21"
      - "22"
    note: false
    quietmode: 0
    scriptarguments:
      extend-context:
        simple: CVE TTP Profiles=content.entity.primaryTag.name
      filter_types:
        simple: TECHNIQUE
      query:
        simple: ${inputs.IoC_CVE}
      sort_property:
        simple: sortDate
    separatecontext: false
    skipunavailable: false
    task:
      brand: Digital Shadows V2
      description: Perform a general search against incidents, threats closed sources,
        etc.
      id: 170c6b32-80c9-4a90-8e16-a82e88f94937
      iscommand: true
      name: ds-search - MITRE TECHNIQUES
      script: Digital Shadows V2|||ds-search
      type: regular
      version: -1
    taskid: 170c6b32-80c9-4a90-8e16-a82e88f94937
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
  "21":
    continueonerrortype: ""
    id: "21"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      desc:
        simple: Associated TTPs
      description:
        simple: ${CVE TTP Profiles}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Adds provided entries to the incident Evidence Board. In playbook, can be positioned after a task to add the previous task's entries to Evidence Board automatically (with no need to provide arguments)
      id: b9c8e600-8626-4e24-8857-e0726806cee5
      iscommand: false
      name: AddEvidence - MITRE TECHNIQUES
      script: AddEvidence
      type: regular
      version: -1
    taskid: b9c8e600-8626-4e24-8857-e0726806cee5
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 545
        }
      }
  "22":
    continueonerrortype: ""
    id: "22"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "23"
      - "24"
    note: false
    quietmode: 0
    scriptarguments:
      extend-context:
        simple: CVE Profile Name=content.entity.primaryTag.name
      filter_types:
        simple: INTELLIGENCE
      query:
        simple: ${inputs.IoC_CVE}
      sort_property:
        simple: sortDate
    separatecontext: false
    skipunavailable: false
    task:
      brand: Digital Shadows V2
      description: Perform a general search against incidents, threats closed sources,
        etc.
      id: aafb94f4-d34a-44b5-8d8b-9f2a2c2a2fc1
      iscommand: true
      name: ds-search - PROFILE INTELLIGENCE
      script: Digital Shadows V2|||ds-search
      type: regular
      version: -1
    taskid: aafb94f4-d34a-44b5-8d8b-9f2a2c2a2fc1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 545
        }
      }
  "23":
    continueonerrortype: ""
    id: "23"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      desc:
        simple: Profiles
      description:
        simple: ${CVE Profile Name}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Adds provided entries to the incident Evidence Board. In playbook, can be positioned after a task to add the previous task's entries to Evidence Board automatically (with no need to provide arguments)
      id: e7b5bb61-eefb-4c7a-8515-0ce179825b7e
      iscommand: false
      name: AddEvidence - INTEL PROFILES
      script: AddEvidence
      type: regular
      version: -1
    taskid: e7b5bb61-eefb-4c7a-8515-0ce179825b7e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
  "24":
    continueonerrortype: ""
    id: "24"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "25"
      - "26"
    note: false
    quietmode: 0
    scriptarguments:
      extend-context:
        simple: CVE Intel Summary=content.entity.summary
      filter_types:
        simple: INTEL_INCIDENT
      query:
        simple: ${inputs.IoC_CVE}
      sort_property:
        simple: sortDate
    separatecontext: false
    skipunavailable: false
    task:
      brand: Digital Shadows V2
      description: Perform a general search against incidents, threats closed sources,
        etc.
      id: 6e1d2333-3f07-488b-86b3-1a75477dbf89
      iscommand: true
      name: ds-search - INTEL UPDATES
      script: Digital Shadows V2|||ds-search
      type: regular
      version: -1
    taskid: 6e1d2333-3f07-488b-86b3-1a75477dbf89
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 720
        }
      }
  "25":
    continueonerrortype: ""
    id: "25"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      desc:
        simple: Summary
      description:
        simple: ${CVE Intel Summary}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Adds provided entries to the incident Evidence Board. In playbook, can be positioned after a task to add the previous task's entries to Evidence Board automatically (with no need to provide arguments)
      id: 2be029dd-5efd-43cf-8a89-a229a6ab088d
      iscommand: false
      name: AddEvidence - INTEL UPDATES
      script: AddEvidence
      type: regular
      version: -1
    taskid: 2be029dd-5efd-43cf-8a89-a229a6ab088d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 895
        }
      }
  "26":
    continueonerrortype: ""
    id: "26"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "27"
    note: false
    quietmode: 0
    scriptarguments:
      extend-context:
        simple: CVE Associated Indicators=content.entity.indicators.title
      filter_types:
        simple: INDICATOR_FEED
      query:
        simple: ${inputs.IoC_CVE}
      sort_property:
        simple: sortDate
    separatecontext: false
    skipunavailable: false
    task:
      brand: Digital Shadows V2
      description: Perform a general search against incidents, threats closed sources,
        etc.
      id: d9a6cfc3-b614-4715-8609-42cc6f205c38
      iscommand: true
      name: ds-search - THREAT FEEDS
      script: Digital Shadows V2|||ds-search
      type: regular
      version: -1
    taskid: d9a6cfc3-b614-4715-8609-42cc6f205c38
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 895
        }
      }
  "27":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${CVE Associated Indicators}
          operator: isEmpty
      label: "yes"
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${CVE Associated Indicators}
          operator: isNotEmpty
      label: "no"
    continueonerrortype: ""
    id: "27"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "30"
      "yes":
      - "13"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 2ff62656-99f5-4a99-8d41-a07e74f1fc24
      iscommand: false
      name: is Associated Indicators blank?
      type: condition
      version: -1
    taskid: 2ff62656-99f5-4a99-8d41-a07e74f1fc24
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 1070
        }
      }
  "30":
    continueonerrortype: ""
    id: "30"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${CVE Associated Indicators}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 7da0fb45-51bc-456a-8e4c-8228d0b9d3a4
      iscommand: false
      name: Print Associated Indicators
      script: Print
      type: regular
      version: -1
    taskid: 7da0fb45-51bc-456a-8e4c-8228d0b9d3a4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 1245
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1290,
        "width": 1670,
        "x": 50,
        "y": 50
      }
    }
  }
