contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.0.0
    itemVersion: 1.0.9
    packID: ""
    packName: Digital Shadows SearchLight
    toServerVersion: ""
description: Enrichment of URL IOC types - sub-playbook for IOC Assessment & Enrichment
  playbook
id: 'Digital Shadows - URL_IoC Assessment & Enrichment_url_v2'
inputs:
- description: A Digital Shadows ShadowSearch query containing URLs
  key: IoC_URL
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: Data
      filters:
      - - left:
            iscontext: true
            value:
              simple: URL
          operator: notContainsGeneral
          right:
            value:
              simple: portal-digitalshadows.com
      root: URL
      transformers:
      - operator: uniq
name: Digital Shadows - URL_IoC Assessment & Enrichment_url_v2
outputs:
- contextPath: DBotScore.Indicator
  description: Indicator Value
  type: string
- contextPath: DBotScore.Type
  description: Indicator Type
  type: string
sourceplaybookid: Digital Shadows - URL_IoC Assessment & Enrichment
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "54"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7fd1819c-3159-40fa-8ea7-ea470bafc0c2
      iscommand: false
      name: ""
      version: -1
    taskid: 7fd1819c-3159-40fa-8ea7-ea470bafc0c2
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 50
        }
      }
  "13":
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 163ba693-6484-4a5a-8c52-94bf3b2d4ff7
      iscommand: false
      name: End
      type: title
      version: -1
    taskid: 163ba693-6484-4a5a-8c52-94bf3b2d4ff7
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1260
        }
      }
  "44":
    continueonerrortype: ""
    id: "44"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "45"
    note: false
    quietmode: 0
    scriptarguments:
      extend-context:
        simple: URL Associated Indicators=content.entity.indicators.title
      filter_types:
        simple: INDICATOR_FEED
      query:
        simple: ${inputs.IoC_URL}
      sort_property:
        simple: sortDate
    separatecontext: false
    skipunavailable: false
    task:
      brand: Digital Shadows V2
      description: Perform a general search against incidents, threats closed sources,
        etc.
      id: 48ca2386-dc14-458f-8842-8c36d81c3e9c
      iscommand: true
      name: ds-search - THREAT FEEDS
      script: Digital Shadows V2|||ds-search
      type: regular
      version: -1
    taskid: 48ca2386-dc14-458f-8842-8c36d81c3e9c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 895
        }
      }
  "45":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${URL Associated Indicators}
          operator: isEmpty
      label: "yes"
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${URL Associated Indicators}
          operator: isNotEmpty
      label: "no"
    continueonerrortype: ""
    id: "45"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "56"
      "yes":
      - "13"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ae8bffb9-db81-4338-892d-e6342dcd3e5e
      iscommand: false
      name: is Associated Indicators blank?
      type: condition
      version: -1
    taskid: ae8bffb9-db81-4338-892d-e6342dcd3e5e
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1070
        }
      }
  "48":
    continueonerrortype: ""
    id: "48"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "49"
      - "44"
    note: false
    quietmode: 0
    scriptarguments:
      extend-context:
        simple: URL Intel Summary=content.entity.summary
      filter_types:
        simple: INTEL_INCIDENT
      query:
        simple: ${inputs.IoC_URL}
      sort_property:
        simple: sortDate
    separatecontext: false
    skipunavailable: false
    task:
      brand: Digital Shadows V2
      description: Perform a general search against incidents, threats closed sources,
        etc.
      id: bfcdfe6d-cf54-46ea-8fd0-11fe2b06e3dd
      iscommand: true
      name: ds-search - INTEL UPDATES
      script: Digital Shadows V2|||ds-search
      type: regular
      version: -1
    taskid: bfcdfe6d-cf54-46ea-8fd0-11fe2b06e3dd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
  "49":
    continueonerrortype: ""
    id: "49"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      desc:
        simple: Summary
      description:
        simple: ${URL Intel Summary}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Adds provided entries to the incident Evidence Board. In playbook, can be positioned after a task to add the previous task's entries to Evidence Board automatically (with no need to provide arguments)
      id: dea5655a-f9c9-4ee7-8e37-d539c3493347
      iscommand: false
      name: AddEvidence - INTEL UPDATES
      script: AddEvidence
      type: regular
      version: -1
    taskid: dea5655a-f9c9-4ee7-8e37-d539c3493347
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 895
        }
      }
  "50":
    continueonerrortype: ""
    id: "50"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "51"
      - "48"
    note: false
    quietmode: 0
    scriptarguments:
      extend-context:
        simple: URL Profile Name=content.entity.primaryTag.name
      filter_types:
        simple: INTELLIGENCE
      query:
        simple: ${inputs.IoC_URL}
      sort_property:
        simple: sortDate
    separatecontext: false
    skipunavailable: false
    task:
      brand: Digital Shadows V2
      description: Perform a general search against incidents, threats closed sources,
        etc.
      id: b1f6741c-f37e-4ac3-88d8-0761aca74442
      iscommand: true
      name: ds-search - PROFILE INTELLIGENCE
      script: Digital Shadows V2|||ds-search
      type: regular
      version: -1
    taskid: b1f6741c-f37e-4ac3-88d8-0761aca74442
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 545
        }
      }
  "51":
    continueonerrortype: ""
    id: "51"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      desc:
        simple: Profiles
      description:
        simple: ${URL Profile Name}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Adds provided entries to the incident Evidence Board. In playbook, can be positioned after a task to add the previous task's entries to Evidence Board automatically (with no need to provide arguments)
      id: 7a57d17d-5bb6-4a68-8835-3ca5fcfcc85c
      iscommand: false
      name: AddEvidence - INTEL PROFILES
      script: AddEvidence
      type: regular
      version: -1
    taskid: 7a57d17d-5bb6-4a68-8835-3ca5fcfcc85c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 720
        }
      }
  "52":
    continueonerrortype: ""
    id: "52"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "53"
      - "50"
    note: false
    quietmode: 0
    scriptarguments:
      extend-context:
        simple: URL TTP Profiles=content.entity.primaryTag.name
      filter_types:
        simple: TECHNIQUE
      query:
        simple: ${inputs.IoC_URL}
      sort_property:
        simple: sortDate
    separatecontext: false
    skipunavailable: false
    task:
      brand: Digital Shadows V2
      description: Perform a general search against incidents, threats closed sources,
        etc.
      id: 473b259f-332c-4df6-8bfd-99a454a4afc9
      iscommand: true
      name: ds-search - MITRE TECHNIQUES
      script: Digital Shadows V2|||ds-search
      type: regular
      version: -1
    taskid: 473b259f-332c-4df6-8bfd-99a454a4afc9
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 370
        }
      }
  "53":
    continueonerrortype: ""
    id: "53"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      desc:
        simple: Associated TTPs
      description:
        simple: ${URL TTP Profiles}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Adds provided entries to the incident Evidence Board. In playbook, can be positioned after a task to add the previous task's entries to Evidence Board automatically (with no need to provide arguments)
      id: 67c74312-b15f-417b-8d2b-43ac9cae7fc8
      iscommand: false
      name: AddEvidence - MITRE TECHNIQUES
      script: AddEvidence
      type: regular
      version: -1
    taskid: 67c74312-b15f-417b-8d2b-43ac9cae7fc8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 545
        }
      }
  "54":
    continueonerrortype: ""
    id: "54"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "55"
      - "52"
    note: false
    quietmode: 0
    scriptarguments:
      extend-context:
        simple: URL Confirmed Activity=total
      filter_types:
        simple: INDICATOR_FEED
      query:
        simple: ${inputs.IoC_URL}
      sort_property:
        simple: sortDate
    separatecontext: false
    skipunavailable: false
    task:
      brand: Digital Shadows V2
      description: Perform a general search against incidents, threats closed sources,
        etc.
      id: 062a63c2-92cf-455d-8ad2-910113465925
      iscommand: true
      name: ds-search - CONFIRMED ACTIVITY
      script: Digital Shadows V2|||ds-search
      type: regular
      version: -1
    taskid: 062a63c2-92cf-455d-8ad2-910113465925
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 195
        }
      }
  "55":
    continueonerrortype: ""
    id: "55"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      desc:
        simple: Confirmed Malicious Activity Count
      description:
        simple: ${URL Confirmed Activity}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Adds provided entries to the incident Evidence Board. In playbook, can be positioned after a task to add the previous task's entries to Evidence Board automatically (with no need to provide arguments)
      id: 2b55d178-f59b-46bb-8c12-4f4056b8456d
      iscommand: false
      name: AddEvidence - CONFIRMED ACTIVITY
      script: AddEvidence
      type: regular
      version: -1
    taskid: 2b55d178-f59b-46bb-8c12-4f4056b8456d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 370
        }
      }
  "56":
    continueonerrortype: ""
    id: "56"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${URL Associated Indicators}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: d95005fe-c105-458d-8444-ccba7209a25e
      iscommand: false
      name: |
        Print Associated Indicators
      script: Print
      type: regular
      version: -1
    taskid: d95005fe-c105-458d-8444-ccba7209a25e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1245
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1290,
        "width": 1670,
        "x": 50,
        "y": 50
      }
    }
  }
