contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.0.0
    itemVersion: 1.0.9
    packID: ""
    packName: Digital Shadows SearchLight
    toServerVersion: ""
description: Enrichment of Domain IOC types - sub-playbook for IOC Assessment & Enrichment
  playbook
id: 'Digital Shadows - Domain_IoC Assessment & Enrichment_v2'
inputs:
- description: A Digital Shadows ShadowSearch query containing domains
  key: IoC_Domain
  playbookInputQuery: null
  required: false
  value:
    complex:
      filters:
      - - left:
            iscontext: true
            value:
              simple: Domain.Name
          operator: notContainsString
          right:
            value:
              simple: portal-digitalshadows.com
      root: Domain.Name
      transformers:
      - operator: uniq
name: Digital Shadows - Domain_IoC Assessment & Enrichment_v2
outputs:
- contextPath: DBotScore.Indicator
  description: Indicator Value
  type: string
- contextPath: DBotScore.Type
  description: Indicator Type
  type: string
sourceplaybookid: Digital Shadows - Domain_IoC Assessment & Enrichment
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "41"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6a66398e-1ffc-41fb-8dac-9aa9568a89ae
      iscommand: false
      name: ""
      version: -1
    taskid: 6a66398e-1ffc-41fb-8dac-9aa9568a89ae
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 50
        }
      }
  "13":
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d80e472b-673a-4456-83e4-e3bf08f8c6f3
      iscommand: false
      name: End
      type: title
      version: -1
    taskid: d80e472b-673a-4456-83e4-e3bf08f8c6f3
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1260
        }
      }
  "31":
    continueonerrortype: ""
    id: "31"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "32"
    note: false
    quietmode: 0
    scriptarguments:
      extend-context:
        simple: Domain Associated Indicators=content.entity.indicators.title
      filter_types:
        simple: INDICATOR_FEED
      query:
        simple: ${inputs.IoC_Domain}
      sort_property:
        simple: sortDate
    separatecontext: false
    skipunavailable: false
    task:
      brand: Digital Shadows V2
      description: Perform a general search against incidents, threats closed sources,
        etc.
      id: 2d0902aa-1bc8-4a6a-8f86-0a87de9d5467
      iscommand: true
      name: ds-search - THREAT FEEDS
      script: Digital Shadows V2|||ds-search
      type: regular
      version: -1
    taskid: 2d0902aa-1bc8-4a6a-8f86-0a87de9d5467
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 895
        }
      }
  "32":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${Domain Associated Indicators}
          operator: isEmpty
      label: "yes"
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${Domain Associated Indicators}
          operator: isNotEmpty
      label: "no"
    continueonerrortype: ""
    id: "32"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "43"
      "yes":
      - "13"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b663c133-c39a-448f-8e0a-af8dc8ecf0d9
      iscommand: false
      name: is Associated Indicators blank?
      type: condition
      version: -1
    taskid: b663c133-c39a-448f-8e0a-af8dc8ecf0d9
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1070
        }
      }
  "35":
    continueonerrortype: ""
    id: "35"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "36"
      - "31"
    note: false
    quietmode: 0
    scriptarguments:
      extend-context:
        simple: Domain Intel Summary=content.entity.summary
      filter_types:
        simple: INTEL_INCIDENT
      query:
        simple: ${inputs.IoC_Domain}
      sort_property:
        simple: sortDate
    separatecontext: false
    skipunavailable: false
    task:
      brand: Digital Shadows V2
      description: Perform a general search against incidents, threats closed sources,
        etc.
      id: 00a6840a-188f-4a14-8cee-6899bd1e4c76
      iscommand: true
      name: ds-search - INTEL UPDATES
      script: Digital Shadows V2|||ds-search
      type: regular
      version: -1
    taskid: 00a6840a-188f-4a14-8cee-6899bd1e4c76
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
  "36":
    continueonerrortype: ""
    id: "36"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      desc:
        simple: Summary
      description:
        simple: ${Domain Intel Summary}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Adds provided entries to the incident Evidence Board. In playbook, can be positioned after a task to add the previous task's entries to Evidence Board automatically (with no need to provide arguments)
      id: 03228abe-4eae-4c8c-822f-d0d55fa26fcc
      iscommand: false
      name: AddEvidence - INTEL UPDATES
      script: AddEvidence
      type: regular
      version: -1
    taskid: 03228abe-4eae-4c8c-822f-d0d55fa26fcc
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 895
        }
      }
  "37":
    continueonerrortype: ""
    id: "37"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "38"
      - "35"
    note: false
    quietmode: 0
    scriptarguments:
      extend-context:
        simple: Domain Profile Name=content.entity.primaryTag.name
      filter_types:
        simple: INTELLIGENCE
      query:
        simple: ${inputs.IoC_Domain}
      sort_property:
        simple: sortDate
    separatecontext: false
    skipunavailable: false
    task:
      brand: Digital Shadows V2
      description: Perform a general search against incidents, threats closed sources,
        etc.
      id: 415c801d-d8b7-4408-8dc3-80c805a5c266
      iscommand: true
      name: ds-search - PROFILE INTELLIGENCE
      script: Digital Shadows V2|||ds-search
      type: regular
      version: -1
    taskid: 415c801d-d8b7-4408-8dc3-80c805a5c266
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 545
        }
      }
  "38":
    continueonerrortype: ""
    id: "38"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      desc:
        simple: Profiles
      description:
        simple: ${Domain Profile Name}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Adds provided entries to the incident Evidence Board. In playbook, can be positioned after a task to add the previous task's entries to Evidence Board automatically (with no need to provide arguments)
      id: 5d49bde6-6a1d-457e-8468-fe0589afb46f
      iscommand: false
      name: AddEvidence - INTEL PROFILES
      script: AddEvidence
      type: regular
      version: -1
    taskid: 5d49bde6-6a1d-457e-8468-fe0589afb46f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 720
        }
      }
  "39":
    continueonerrortype: ""
    id: "39"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "40"
      - "37"
    note: false
    quietmode: 0
    scriptarguments:
      extend-context:
        simple: Domain TTP Profiles=content.entity.primaryTag.name
      filter_types:
        simple: TECHNIQUE
      query:
        simple: ${inputs.IoC_Domain}
      sort_property:
        simple: sortDate
    separatecontext: false
    skipunavailable: false
    task:
      brand: Digital Shadows V2
      description: Perform a general search against incidents, threats closed sources,
        etc.
      id: 94e8a075-1c46-46a8-8168-797798e2627a
      iscommand: true
      name: ds-search - MITRE TECHNIQUES
      script: Digital Shadows V2|||ds-search
      type: regular
      version: -1
    taskid: 94e8a075-1c46-46a8-8168-797798e2627a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 370
        }
      }
  "40":
    continueonerrortype: ""
    id: "40"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      desc:
        simple: Associated TTPs
      description:
        simple: ${Domain TTP Profiles}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Adds provided entries to the incident Evidence Board. In playbook, can be positioned after a task to add the previous task's entries to Evidence Board automatically (with no need to provide arguments)
      id: 58dd8fc9-920d-470a-8648-3bc62344c9fd
      iscommand: false
      name: AddEvidence - MITRE TECHNIQUES
      script: AddEvidence
      type: regular
      version: -1
    taskid: 58dd8fc9-920d-470a-8648-3bc62344c9fd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 545
        }
      }
  "41":
    continueonerrortype: ""
    id: "41"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "42"
      - "39"
    note: false
    quietmode: 0
    scriptarguments:
      extend-context:
        simple: Domain Suspected Activity=total
      filter_types:
        simple: INDICATOR_FEED
      query:
        simple: ${inputs.IoC_Domain}
      sort_property:
        simple: sortDate
    separatecontext: false
    skipunavailable: false
    task:
      brand: Digital Shadows V2
      description: Perform a general search against incidents, threats closed sources,
        etc.
      id: e5811f32-ec3c-4dbb-81f8-4c1489505d4c
      iscommand: true
      name: ds-search - SUSPECTED ACTIVITY
      script: Digital Shadows V2|||ds-search
      type: regular
      version: -1
    taskid: e5811f32-ec3c-4dbb-81f8-4c1489505d4c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 195
        }
      }
  "42":
    continueonerrortype: ""
    id: "42"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      desc:
        simple: Confirmed Suspected Activity Count
      description:
        simple: ${Domain Suspected Activity}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Adds provided entries to the incident Evidence Board. In playbook, can be positioned after a task to add the previous task's entries to Evidence Board automatically (with no need to provide arguments)
      id: 7ea89eae-685d-42d4-88a7-01ea3d218560
      iscommand: false
      name: AddEvidence - SUSPECTED ACTIVITY
      script: AddEvidence
      type: regular
      version: -1
    taskid: 7ea89eae-685d-42d4-88a7-01ea3d218560
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 370
        }
      }
  "43":
    continueonerrortype: ""
    id: "43"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${Domain Associated Indicators}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: e2f5c4ca-1821-4a59-860b-dd7edcc9df22
      iscommand: false
      name: Print Associated Indicators
      script: Print
      type: regular
      version: -1
    taskid: e2f5c4ca-1821-4a59-860b-dd7edcc9df22
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1245
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1290,
        "width": 1670,
        "x": 50,
        "y": 50
      }
    }
  }
