contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.0.0
    itemVersion: 1.0.9
    packID: ""
    packName: Digital Shadows SearchLight
    toServerVersion: ""
description: Enrich indicators by providing intelligence and more associated indicators
  based on confirmed reporting in Digital Shadows SearchLight.
id: 'Digital Shadows - IoC Assessment & Enrichment_v2'
inputs:
- description: An IP address for assessment and enrichment
  key: IoC_IP
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: Address
      root: IP
      transformers:
      - operator: uniq
- description: A CVE for assessment and enrichment
  key: IoC_CVE
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: ID
      root: CVE
      transformers:
      - operator: uniq
- description: A domain for assessment and enrichment
  key: IoC_Domain
  playbookInputQuery: null
  required: false
  value:
    complex:
      filters:
      - - left:
            iscontext: true
            value:
              simple: Domain.Name
          operator: notContainsString
          right:
            value:
              simple: portal-digitalshadows.com
      root: Domain.Name
      transformers:
      - operator: uniq
- description: A URL for assessment and enrichment
  key: IoC_URL
  playbookInputQuery: null
  required: false
  value:
    complex:
      filters:
      - - left:
            iscontext: true
            value:
              simple: URL.Data
          operator: notContainsString
          right:
            value:
              simple: portal-digitalshadows.com
      root: URL.Data
      transformers:
      - operator: uniq
- description: A MD5 hash for assessment and enrichment
  key: IoC_MD5
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: MD5
      root: File
      transformers:
      - operator: uniq
- description: A SHA256 hash for assessment and enrichment
  key: IoC_SHA256
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: SHA256
      root: File
      transformers:
      - operator: uniq
- description: A SHA1 hash for assessment and enrichment
  key: IoC_SHA1
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: SHA1
      root: File
      transformers:
      - operator: uniq
name: Digital Shadows - IoC Assessment & Enrichment_v2
outputs:
- contextPath: DBotScore.Indicator
  description: Indicator Value
  type: string
- contextPath: DBotScore.Type
  description: Indicator Type
  type: string
sourceplaybookid: Digital Shadows - IoC Assessment & Enrichment
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 26c6051b-dd8f-4e42-8b4d-49fe612f05ee
      iscommand: false
      name: ""
      version: -1
    taskid: 26c6051b-dd8f-4e42-8b4d-49fe612f05ee
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "13":
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 792460d8-d723-4dfa-88a7-03af9d4cae39
      iscommand: false
      name: End
      type: title
      version: -1
    taskid: 792460d8-d723-4dfa-88a7-03af9d4cae39
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2645
        }
      }
  "16":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.IoC_IP
          operator: isNotEmpty
      label: "yes"
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.IoC_IP
          operator: isEmpty
      label: "no"
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "30"
      "yes":
      - "54"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a40dafdc-ced5-4664-8e82-1843b9faf58f
      iscommand: false
      name: Is an IP Address Included?
      type: condition
      version: -1
    taskid: a40dafdc-ced5-4664-8e82-1843b9faf58f
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "17":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.IoC_CVE
          operator: isNotEmpty
      label: "yes"
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.IoC_CVE
          operator: isEmpty
      label: "no"
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "13"
      "yes":
      - "60"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 95667365-0004-4290-85fe-2071303ef993
      iscommand: false
      name: Is a CVE Included?
      type: condition
      version: -1
    taskid: 95667365-0004-4290-85fe-2071303ef993
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2295
        }
      }
  "30":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.IoC_Domain
          operator: isNotEmpty
      label: "yes"
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.IoC_Domain
          operator: isEmpty
      label: "no"
    continueonerrortype: ""
    id: "30"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "43"
      "yes":
      - "55"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4fe61d32-6d27-4ccc-8bdc-f18a1a7803f9
      iscommand: false
      name: Is a Domain Included?
      type: condition
      version: -1
    taskid: 4fe61d32-6d27-4ccc-8bdc-f18a1a7803f9
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "43":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.IoC_URL
          operator: isNotEmpty
      label: "yes"
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.IoC_URL
          operator: isEmpty
      label: "no"
    continueonerrortype: ""
    id: "43"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "44"
      "yes":
      - "56"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4b2a5654-7208-4236-86d0-65e62c4a7a99
      iscommand: false
      name: Is a URL Included?
      type: condition
      version: -1
    taskid: 4b2a5654-7208-4236-86d0-65e62c4a7a99
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
  "44":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.IoC_MD5
          operator: isNotEmpty
      label: "yes"
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.IoC_MD5
          operator: isEmpty
      label: "no"
    continueonerrortype: ""
    id: "44"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "45"
      "yes":
      - "57"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 78a15d3f-61b9-439f-8679-a091a17179bb
      iscommand: false
      name: Is an MD5 Included?
      type: condition
      version: -1
    taskid: 78a15d3f-61b9-439f-8679-a091a17179bb
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
  "45":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.IoC_SHA256
          operator: isNotEmpty
      label: "yes"
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.IoC_SHA256
          operator: isEmpty
      label: "no"
    continueonerrortype: ""
    id: "45"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "46"
      "yes":
      - "58"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: beaf8a38-565b-4560-810e-838cad30b43a
      iscommand: false
      name: Is a SHA256 Included?
      type: condition
      version: -1
    taskid: beaf8a38-565b-4560-810e-838cad30b43a
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1595
        }
      }
  "46":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.IoC_SHA1
          operator: isNotEmpty
      label: "yes"
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.IoC_SHA1
          operator: isEmpty
      label: "no"
    continueonerrortype: ""
    id: "46"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "17"
      "yes":
      - "59"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 46050db4-8ded-4bc6-8c53-ec0ddc201796
      iscommand: false
      name: Is a SHA1 Included?
      type: condition
      version: -1
    taskid: 46050db4-8ded-4bc6-8c53-ec0ddc201796
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1945
        }
      }
  "54":
    continueonerrortype: ""
    id: "54"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "30"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 4551283c-8e23-4ea8-8a0e-a2127b9f0526
      iscommand: false
      name: Digital Shadows - IP_IoC Assessment & Enrichment_v2
      playbookId: 'Digital Shadows - IP_IoC Assessment & Enrichment_v2'
      type: playbook
      version: -1
    taskid: 4551283c-8e23-4ea8-8a0e-a2127b9f0526
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 370
        }
      }
  "55":
    continueonerrortype: ""
    id: "55"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "43"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 3ad78112-8b6f-452a-8b00-18835c2d0fc8
      iscommand: false
      name: Digital Shadows - Domain_IoC Assessment & Enrichment_v2
      playbookId: 'Digital Shadows - Domain_IoC Assessment & Enrichment_v2'
      type: playbook
      version: -1
    taskid: 3ad78112-8b6f-452a-8b00-18835c2d0fc8
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 720
        }
      }
  "56":
    continueonerrortype: ""
    id: "56"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "44"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: ff9b2fff-538b-465b-8051-22c2f10e3ef9
      iscommand: false
      name: Digital Shadows - URL_IoC Assessment & Enrichment_url_v2
      playbookId: 'Digital Shadows - URL_IoC Assessment & Enrichment_url_v2'
      type: playbook
      version: -1
    taskid: ff9b2fff-538b-465b-8051-22c2f10e3ef9
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1070
        }
      }
  "57":
    continueonerrortype: ""
    id: "57"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "45"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 14d272da-b2fc-4259-81f7-431c777c83cf
      iscommand: false
      name: Digital Shadows - MD5_IoC Assessment & Enrichment_v2
      playbookId: 'Digital Shadows - MD5_IoC Assessment & Enrichment_v2'
      type: playbook
      version: -1
    taskid: 14d272da-b2fc-4259-81f7-431c777c83cf
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1420
        }
      }
  "58":
    continueonerrortype: ""
    id: "58"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "46"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: cca5685f-473e-4f6e-873a-27ce77b254f5
      iscommand: false
      name: Digital Shadows - SHA256_IoC Assessment & Enrichment_v2
      playbookId: 'Digital Shadows - SHA256_IoC Assessment & Enrichment_v2'
      type: playbook
      version: -1
    taskid: cca5685f-473e-4f6e-873a-27ce77b254f5
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1770
        }
      }
  "59":
    continueonerrortype: ""
    id: "59"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "17"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: ead2116b-cbc1-47bb-83f9-4eaabdd36380
      iscommand: false
      name: Digital Shadows - SHA1_IoC Assessment & Enrichment_v2
      playbookId: 'Digital Shadows - SHA1_IoC Assessment & Enrichment_v2'
      type: playbook
      version: -1
    taskid: ead2116b-cbc1-47bb-83f9-4eaabdd36380
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 2120
        }
      }
  "60":
    continueonerrortype: ""
    id: "60"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: b151ef0d-77da-484a-8d2a-db6dfd4863af
      iscommand: false
      name: Digital Shadows - CVE_IoC Assessment & Enrichment_v2
      playbookId: 'Digital Shadows - CVE_IoC Assessment & Enrichment_v2'
      type: playbook
      version: -1
    taskid: b151ef0d-77da-484a-8d2a-db6dfd4863af
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 2470
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "16_54_yes": 0.9,
      "30_55_yes": 0.9,
      "43_56_yes": 0.9,
      "44_57_yes": 0.9
    },
    "paper": {
      "dimensions": {
        "height": 2660,
        "width": 492.5,
        "x": 50,
        "y": 50
      }
    }
  }
