contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.0.0
    itemVersion: 1.0.9
    packID: ""
    packName: Digital Shadows SearchLight
    toServerVersion: ""
description: Enrichment of IP IOC types - sub-playbook for IOC Assessment & Enrichment
  playbook
id: 'Digital Shadows - IP_IoC Assessment & Enrichment_v2'
inputs:
- description: A Digital Shadows ShadowSearch query containing IP addresses
  key: IoC_IP
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: Address
      filters:
      - - left:
            iscontext: true
            value:
              simple: IP
          operator: notContainsGeneral
          right:
            value:
              simple: 0.0.0.0
      root: IP
      transformers:
      - operator: uniq
name: Digital Shadows - IP_IoC Assessment & Enrichment_v2
outputs:
- contextPath: DBotScore.Indicator
  description: Indicator Value
  type: string
- contextPath: DBotScore.Type
  description: Indicator Type
  type: string
sourceplaybookid: Digital Shadows - IP_IoC Assessment & Enrichment
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "17"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e6b786dd-ea95-4297-8fe3-1f812d7f17d4
      iscommand: false
      name: ""
      version: -1
    taskid: e6b786dd-ea95-4297-8fe3-1f812d7f17d4
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 50
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      extend-context:
        simple: IP Associated Indicators=content.entity.indicators.title
      filter_types:
        simple: INDICATOR_FEED
      query:
        simple: ${inputs.IoC_IP}
      sort_property:
        simple: sortDate
    separatecontext: false
    skipunavailable: false
    task:
      brand: Digital Shadows V2
      description: Perform a general search against incidents, threats closed sources,
        etc.
      id: a4cd2b5e-6481-4952-8056-5cd3fac4eda5
      iscommand: true
      name: ds-search - THREAT FEEDS
      script: Digital Shadows V2|||ds-search
      type: regular
      version: -1
    taskid: a4cd2b5e-6481-4952-8056-5cd3fac4eda5
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 895
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      extend-context:
        simple: IP Intel Summary=content.entity.summary
      filter_types:
        simple: INTEL_INCIDENT
      query:
        simple: ${inputs.IoC_IP}
      sort_property:
        simple: sortDate
    separatecontext: false
    skipunavailable: false
    task:
      brand: Digital Shadows V2
      description: Perform a general search against incidents, threats closed sources,
        etc.
      id: 6cd919ad-7874-40bd-843a-0781d29f3c03
      iscommand: true
      name: ds-search - INTEL UPDATES
      script: Digital Shadows V2|||ds-search
      type: regular
      version: -1
    taskid: 6cd919ad-7874-40bd-843a-0781d29f3c03
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
  "8":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${IP Associated Indicators}
          operator: isEmpty
      label: "yes"
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${IP Associated Indicators}
          operator: isNotEmpty
      label: "no"
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "16"
      "yes":
      - "13"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: fef4b210-0b39-4d2c-8f8c-ad99f6eccff3
      iscommand: false
      name: is Associated Indicators blank?
      type: condition
      version: -1
    taskid: fef4b210-0b39-4d2c-8f8c-ad99f6eccff3
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1070
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      desc:
        simple: Summary
      description:
        simple: ${IP Intel Summary}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Adds provided entries to the incident Evidence Board. In playbook, can be positioned after a task to add the previous task's entries to Evidence Board automatically (with no need to provide arguments)
      id: 211651a2-36a9-4ee2-8f16-c681b63e5ae8
      iscommand: false
      name: AddEvidence - INTEL UPDATES
      script: AddEvidence
      type: regular
      version: -1
    taskid: 211651a2-36a9-4ee2-8f16-c681b63e5ae8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 895
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      desc:
        simple: Profiles
      description:
        simple: ${IP Profile Name}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Adds provided entries to the incident Evidence Board. In playbook, can be positioned after a task to add the previous task's entries to Evidence Board automatically (with no need to provide arguments)
      id: 8abd417f-3a2e-4dd9-8544-38063e65dffe
      iscommand: false
      name: AddEvidence - INTEL PROFILES
      script: AddEvidence
      type: regular
      version: -1
    taskid: 8abd417f-3a2e-4dd9-8544-38063e65dffe
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 720
        }
      }
  "11":
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      desc:
        simple: Associated TTPs
      description:
        simple: ${IP TTP Profiles}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Adds provided entries to the incident Evidence Board. In playbook, can be positioned after a task to add the previous task's entries to Evidence Board automatically (with no need to provide arguments)
      id: 06a27aa3-bfaa-4801-8e5e-5aa7b6a0f4ba
      iscommand: false
      name: AddEvidence - MITRE TECHNIQUES
      script: AddEvidence
      type: regular
      version: -1
    taskid: 06a27aa3-bfaa-4801-8e5e-5aa7b6a0f4ba
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 545
        }
      }
  "12":
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      desc:
        simple: Suspected Malicious Activity Count
      description:
        simple: ${IP Suspected Activity}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Adds provided entries to the incident Evidence Board. In playbook, can be positioned after a task to add the previous task's entries to Evidence Board automatically (with no need to provide arguments)
      id: 0e627857-ebd8-4f5d-8968-138f0376b55a
      iscommand: false
      name: AddEvidence - SUSPECTED ACTIVITY
      script: AddEvidence
      type: regular
      version: -1
    taskid: 0e627857-ebd8-4f5d-8968-138f0376b55a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 370
        }
      }
  "13":
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 244d7e17-80cb-4466-89ed-fb71a6cca9ef
      iscommand: false
      name: End
      type: title
      version: -1
    taskid: 244d7e17-80cb-4466-89ed-fb71a6cca9ef
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1260
        }
      }
  "16":
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${IP Associated Indicators}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 97e25be5-a4a1-4ac2-8536-7fcc674190a4
      iscommand: false
      name: Print Associated Indicators
      script: Print
      type: regular
      version: -1
    taskid: 97e25be5-a4a1-4ac2-8536-7fcc674190a4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1245
        }
      }
  "17":
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "18"
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      extend-context:
        simple: IP Suspected Activity=total
      filter_datePeriod:
        simple: P12M
      filter_types:
        simple: INDICATOR_FEED
      query:
        simple: ${inputs.IoC_IP}
      sort_property:
        simple: sortDate
    separatecontext: false
    skipunavailable: false
    task:
      brand: Digital Shadows V2
      description: Perform a general search against incidents, threats closed sources,
        etc.
      id: 95c02293-3cdc-428b-8e01-91072dd2b370
      iscommand: true
      name: ds-search - SUSPECTED ACTIVITY
      script: Digital Shadows V2|||ds-search
      type: regular
      version: -1
    taskid: 95c02293-3cdc-428b-8e01-91072dd2b370
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 185
        }
      }
  "18":
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
      - "19"
    note: false
    quietmode: 0
    scriptarguments:
      extend-context:
        simple: IP TTP Profiles=content.entity.primaryTag.name
      filter_types:
        simple: TECHNIQUE
      query:
        simple: ${inputs.IoC_IP}
      sort_property:
        simple: sortDate
    separatecontext: false
    skipunavailable: false
    task:
      brand: Digital Shadows V2
      description: Perform a general search against incidents, threats closed sources,
        etc.
      id: dea76125-9d17-4438-80bf-8cdadef133e8
      iscommand: true
      name: ds-search - MITRE TECHNIQUES
      script: Digital Shadows V2|||ds-search
      type: regular
      version: -1
    taskid: dea76125-9d17-4438-80bf-8cdadef133e8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 870,
          "y": 360
        }
      }
  "19":
    continueonerrortype: ""
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      extend-context:
        simple: IP Profile Name=content.entity.primaryTag.name
      filter_types:
        simple: INTELLIGENCE
      query:
        simple: ${inputs.IoC_IP}
      sort_property:
        simple: sortDate
    separatecontext: false
    skipunavailable: false
    task:
      brand: Digital Shadows V2
      description: Perform a general search against incidents, threats closed sources,
        etc.
      id: 8a6cbb2a-76a2-462e-8fa3-426bca5ce7d7
      iscommand: true
      name: ds-search - PROFILE INTELLIGENCE
      script: Digital Shadows V2|||ds-search
      type: regular
      version: -1
    taskid: 8a6cbb2a-76a2-462e-8fa3-426bca5ce7d7
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 645,
          "y": 545
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1290,
        "width": 1670,
        "x": 50,
        "y": 50
      }
    }
  }
